base/urls.py
from django.urls import path
from .views import home

urlpatterns = [
    path('', home, name='home')
]

blog/urls.py
from django.urls import path, re_path

from .views import (
    post_detail,
    post_list,
    post_create,
    post_edit,
    subscriber_view,
    sub_conf,
)

app_name = 'blog'

urlpatterns = [
    path('subscribe/', subscriber_view, name='subscribe'),
    path('edit/<slug:slug>/', post_edit, name='post_edit'),
    path('create/', post_create, name='post_create'),
    path('<slug:slug>/', post_detail, name='post_detail'),
    path('', post_list, name='post_list'),
    re_path(r'^sub_conf/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,32})/$',
        sub_conf, name='sub_conf'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    # path('admin/', admin.site.urls),
    path(settings.ADMIN_PATH + '/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('auth/', include('custom_auth.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('', include('base.urls')),
]
# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth import get_user_model

# 3rd Party
from tinymce import models as tinymce_models
from taggit.managers import TaggableManager

UserModel = get_user_model()


class TimeStampMixin(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Post(TimeStampMixin):
    title = models.CharField(max_length=128, blank=False, null=False, unique=True)
    slug = models.SlugField(blank=True, null=True)
    description = tinymce_models.HTMLField(blank=True, null=True)
    tags = TaggableManager()
    link = models.URLField(blank=True, null=True)
    image = models.ImageField(upload_to='uploaded', blank=True, null=True, default='default.png')
    published = models.BooleanField(blank=True, null=True, default=False)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        if self.image == '':  # Change image to default when image is deleted
            self.image = 'images/default.png'
        super(Post, self).save(*args, **kwargs)


class Subscriber(TimeStampMixin):
    email = models.EmailField(blank=False, null=False, unique=True)
    confirmed = models.BooleanField(blank=True, null=True, default=False)

    def __str__(self):
        return self.email

base/views.py
from multiprocessing import context
from django.shortcuts import render

def home(request):
    context = {'active': 'home'}
    return render(request, 'home.html', context)

base/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="#">
    <title>Portfolio</title>
    <script src="{% static 'js/3rd_party/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'js/3rd_party/anime.min.js' %}"></script>
    <script src="{% static 'js/3rd_party/tinymce_5.10.3/tinymce/tinymce.min.js' %}"></script>
    {{form.media}}
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <script src="https://kit.fontawesome.com/61b5fec5d5.js" crossorigin="anonymous"></script>
</head>
<body>

    <!-- Themes -->
    <input type="checkbox" name="" id="theme_toggle" checke>
    <div id="theme_container" class="dark-mode">

        <!-- Messages -->
        <div class="message__container">
            {% for message in messages %}
                <div class="message message__{{ message.tags }}">
                    <span>{{ message|safe }}</span>
                    <i class="fas fa-times-circle"></i>
                </div>
            {% endfor %}
        </div>

        <!-- Subscribe Form -->
        <div class="cover hidden"></div>
        <div class="popup hidden" data-popup-sub=""> <!-- data is for popup_sub.js -->
            <div>
                
                <form action="{% url 'blog:subscribe' %}" method="POST" class="sub_form">
                    {% csrf_token %}
                    <p>Subscribe to be notified of new articles and projects!</p>
                    <div class="sub_form__email_container">
                        <input type="email" name="email" maxlength="254" placeholder="email..."
                            required id="id_email">
                    </div>
                    <div class="sub_form__submit_container">
                        <input type="submit" value="Subscribe">
                    </div>
                </form>
            </div>
        </div>

        <!-- Navigation -->
        {% include "partials/navigation.html" %}

        <div id="page">
            {% block content %}
            {% endblock content %}
        </div>

        <!-- % include "partials/footer.html" % -->

    </div>

    <!-- Javascript -->
    <script src="{% static 'js/base/popup_sub.js' %}"></script>
    <script src="{% static 'js/base/messages.js' %}"></script>
    <script src="{% static 'js/base/local_storage.js' %}"></script>
    <script src="{% static 'js/base/sub_request.js' %}"></script>

</body>
</html>

base/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="home">
    <h2 class="home__title--1">Hey, I'm Sean!</h2>
    <h3 class="home__title--2">
        A Full Stack Web Developer based in London
    </h3>
    <img src="{% static 'images/home.svg' %}" alt="A Cartoon of a Programmer" class="home__image">
    
    <div class="btn home__btn">
        <a href="{% url 'blog:post_list' %}">View Posts</a>
    </div>
</div>

{% endblock content %}