base/urls.py
from django.urls import path
from .views import home

urlpatterns = [
    path('', home, name='home')
]

blog/urls.py
from django.urls import path, re_path

from .views import (
    post_detail,
    post_list,
    post_create,
    post_edit,
    subscriber_view,
    sub_conf,
)

app_name = 'blog'

urlpatterns = [
    path('subscribe/', subscriber_view, name='subscribe'),
    path('edit/<slug:slug>/', post_edit, name='post_edit'),
    path('create/', post_create, name='post_create'),
    path('<slug:slug>/', post_detail, name='post_detail'),
    path('', post_list, name='post_list'),
    re_path(r'^sub_conf/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,32})/$',
        sub_conf, name='sub_conf'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    # path('admin/', admin.site.urls),
    path(settings.ADMIN_PATH + '/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('auth/', include('custom_auth.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('', include('base.urls')),
]
# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth import get_user_model

# 3rd Party
from tinymce import models as tinymce_models
from taggit.managers import TaggableManager

UserModel = get_user_model()


class TimeStampMixin(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Post(TimeStampMixin):
    title = models.CharField(max_length=128, blank=False, null=False, unique=True)
    slug = models.SlugField(blank=True, null=True)
    description = tinymce_models.HTMLField(blank=True, null=True)
    tags = TaggableManager()
    link = models.URLField(blank=True, null=True)
    image = models.ImageField(upload_to='uploaded', blank=True, null=True, default='default.png')
    published = models.BooleanField(blank=True, null=True, default=False)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        if self.image == '':  # Change image to default when image is deleted
            self.image = 'images/default.png'
        super(Post, self).save(*args, **kwargs)


class Subscriber(TimeStampMixin):
    email = models.EmailField(blank=False, null=False, unique=True)
    confirmed = models.BooleanField(blank=True, null=True, default=False)

    def __str__(self):
        return self.email

blog/forms.py
from django import forms

# Custom
from .models import Post, Subscriber

# 3rd Party
from tinymce.widgets import TinyMCE


class PostForm(forms.ModelForm):
    description = forms.CharField(widget=TinyMCE(attrs={'cols': 80, 'rows': 30}))
    
    class Meta:
        model = Post
        exclude = ('slug', 'created_at', 'updated_at',) 


class SubscriberForm(forms.ModelForm):

    class Meta:
        model = Subscriber
        fields = ('email',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["email"].widget.attrs["placeholder"] = "email..."
        # self.fields["email"].widget.attrs["class"] = "input"

blog/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator

# Custom
from .models import Post, Subscriber
from .forms import PostForm, SubscriberForm

from .send_mail import send_mail
from django.utils.encoding import force_str
from django.utils.http import urlsafe_base64_decode
from .tokens import account_activation_token

# 3rd Party
from taggit.models import Tag


@login_required
def post_create(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            form.save()
            title = form.cleaned_data.get('title')
            post = Post.objects.get(title=title)
            messages.success(request, 'Post created!')
            return redirect('blog:post_detail', slug=post.slug)
    else:
        form = PostForm()

    context = {'active': 'post_create', 'form': form}
    return render(request, 'blog/post_create.html', context)

@login_required
def post_edit(request, slug):
    post = Post.objects.get(slug=slug)
    
    if request.method == 'POST':
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            messages.success(request, 'Post edited!')
            return redirect('blog:post_detail', slug=post.slug)
    else:
        form = PostForm(instance=post)

    context = {'active': 'post_edit', 'form': form, 'post': post}
    return render(request, 'blog/post_edit.html', context)


def post_list(request):

    posts = Post.objects.filter(published=True).order_by('-created_at')

    post_title = request.GET.get('post-title')
    post_type = request.GET.get('post-type')
    post_count = request.GET.get('post-count')

    if post_title is not None:
        try:
            posts = posts.filter(title__icontains=post_title)
        except Exception as e:
            print(e)
    if post_type is not None:
        if post_type != 'empty':
            try:
                tag = Tag.objects.get(name=post_type)
                posts = posts.filter(tags=tag.id)
            except Exception as e:
                print(e)

    if post_count is not None:
        paginator = Paginator(posts, post_count)
    else:
        paginator = Paginator(posts, 5)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    tags = Tag.objects.all()

    # Determine 'active' attribute
    if post_type is not None:
        active = str(post_type + 's')
    else:
        active = 'post_list'
        
    context = {'active': active, 'page_obj': page_obj, 'tags': tags}
    return render(request, 'blog/post_list.html', context)


def post_detail(request, slug):
    post = None
    try:
        post = Post.objects.get(slug=slug)
    except Exception as e:
        print(e)
        messages.error(request, f'Post with slug "{slug}" does not exist.')
        return render(request, 'home.html', {})

    context = {'active': 'post_detail', 'post': post}
    return render(request, 'blog/post_detail.html', context)


def subscriber_view(request):
    
    if request.method == 'POST':
        form = SubscriberForm(request.POST)
        print('Request Method is POST')
        if form.is_valid():
            print('Is Valid? Yes')
            form.save()

            # Send email to subscriber to confirm account
            email = form.cleaned_data.get('email')
            sub = Subscriber.objects.get(email=email)
            if email is not None:
                sent = send_mail(request, sub)
                if sent:
                    messages.success(request, 'Almost there! A confirmation email has been sent to your account.')
                else:
                    messages.error(request, 'Error: Could not send email!')
            return redirect('home')
        else:
            email = request.POST.get('email')
            sub = Subscriber.objects.get(email=email)
            if sub.confirmed:
                messages.warning(request, 'This email is already subscribed')
                return redirect('home')
            if email is not None:
                sent = send_mail(request, sub)
                if sent:
                    messages.success(request, 'Almost there! A confirmation email has been sent to your account.')
                else:
                    messages.error(request, 'Error: Could not send email!')
            return redirect('home')

    else:
        form = SubscriberForm()

    context = {'active': 'post_subscribe', 'form': form}
    return render(request, 'blog/subscribe.html', context)


def sub_conf(request, uidb64, token):

    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        sub = Subscriber.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, Subscriber.DoesNotExist):
        sub = None

    if sub is not None and account_activation_token.check_token(sub, token):
        sub.confirmed = True
        sub.save()

        messages.success(request, 'Email has been verified!')
    else:
        messages.error(request, 'Activation link is invalid')

    return redirect('home')

blog/templates/blog/post_create.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<form action="{% url 'blog:post_create' %}" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Submit">
</form>

{% endblock content %}

blog/templates/blog/post_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="post_detail">
    <!-- {% if user.is_authenticated %}
        <p class="post_detail__edit">
            <a href="{% url 'blog:post_edit' post.slug %}">Edit</a>
        </p>
    {% endif %} -->
    
    <div class="post_detail__image">
        <img src="{{ post.image.url }}" alt="" width="150">
    </div>
    
    <div class="post_detail__title">{{post.title}}</div>

    {% if post.link %}
        <div class="btn post_detail__link">
            <a href="{{ post.link }}" target="_blank" rel="noopener noreferrer">Visit Website</a>
        </div>
    {% endif %}
    
    <div class="container">    
        <div class="post_detail__description">
            <!-- Only displays "Description:" if the post is an article -->
            {% for tag in post.tags.all %}
                {% if tag.name != 'article' %}
                    <div style="font-size: 1.1rem; margin-bottom: 1rem;">Description:</div>
                {% endif %}
            {% endfor %} 

            {{post.description|safe}}
        </div>
    </div>

    <!-- <div class="post_detail__tags">
        Tags: {% for tag in post.tags.all %}{{tag}}{% endfor %}
    </div> -->
</div>

{% endblock content %}

blog/templates/blog/post_edit.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<form action="{% url 'blog:post_edit' post.slug %}" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Submit Edit">
</form>

{% endblock content %}

blog/templates/blog/post_list.html
{% extends 'base.html' %}
{% load static %}
{% load transform %}
{% block content %}
<form action="{% url 'blog:post_list' %}" method="GET" class="search_form">

    <input type="text" name="post-title" id="" placeholder="title">

    <select name="post-type" id="">
        <option value="empty">Choose a type...</option>
        {% for tag in tags %}
            <option value="{{tag}}">{{tag|title}}</option>
        {% endfor %}
    </select>

    <select name="post-count" id="">
        <option value="5">5</option>
        <option value="5">10</option>
        <option value="15">15</option>
        <option value="20">20</option>
        <option value="25">25</option>
    </select>

    <input type="submit" value="Search">
</form>


<div class="post_list">
    {% for post in page_obj %}
        <div class="post_list__item">
            <a href="{% url 'blog:post_detail' post.slug %}" class="post_list__item__link"></a>
            <div class="post_list__item__cover">
                <div class="post_list__item__cover__button">
                    <p>Read More</p>
                </div>
            </div>
            <div class="img-container">
                <img src="{% if post.image %}{{ post.image.url }}{% endif %}" alt=""/>
            </div>
            
            <div class="post_list__item__details">
                <h3 class="post_list__item__details__title">
                    {{post.title}}
                </h3>
                <div class="post_list__item__details__description">
                    {% autoescape on %}
                        {{post.description|safe|truncatechars_html:180}}
                    {% endautoescape %}
                </div>
            </div>
        </div>
    {% empty %}
        <p>No posts :(</p>
    {% endfor %}
</div>


<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <!-- <a href="?page=1">&laquo; first</a> -->
            <a href="?{% query_transform page=1 %}">&laquo; first</a>
            <!-- <a href="?page={{ page_obj.previous_page_number }}">previous</a> -->
            <a href="?{% query_transform page=page_obj.previous_page_number %}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <!-- <a href="?page={{ page_obj.next_page_number }}">next</a> -->
            <a href="?{% query_transform page=page_obj.next_page_number %}">next</a>
            <!-- <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a> -->
            <a href="?{% query_transform page=page_obj.paginator.num_pages %}">last &raquo;</a>
        {% endif %}
    </span>
</div>

{% endblock content %}

blog/templates/blog/subscribe.html
<!-- TODO: Change this into a partial -->
{% extends 'base.html' %}
{% load static %}

{% block content %}

<h1>Subscribe</h1>

<form action="{% url 'blog:subscribe' %}" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Subscribe">
</form>

{% endblock content %}